import { PlatformConfig, PlatformTarget } from './types';

export const PLATFORM_PROFILES: Record<PlatformTarget, PlatformConfig> = {
  android: {
    id: 'android',
    name: 'Android Device (Test Pipeline)',
    description: 'Arm64 JNI pipeline profile with low-latency touch pooling, 60Hz frame pacing, and hardware vibration triggers.',
    maxMemoryMB: 48,
    targetFPS: 60,
    batchCapacity: 1024,
    particleLimit: 250,
    enableCRTShader: false,
    enableHaptics: true,
    touchControllerStyle: 'joystick',
    inputPollingRateHz: 120,
    textureFilter: 'nearest',
  },
  ios: {
    id: 'ios',
    name: 'iOS Mobile / iPadOS PWA',
    description: 'High-DPI Retina profile with multi-touch gesture detection and smooth 60/120 FPS dynamic pacing.',
    maxMemoryMB: 64,
    targetFPS: 60,
    batchCapacity: 1536,
    particleLimit: 300,
    enableCRTShader: false,
    enableHaptics: true,
    touchControllerStyle: 'joystick',
    inputPollingRateHz: 120,
    textureFilter: 'linear',
  },
  desktop: {
    id: 'desktop',
    name: 'Desktop (Ultra / HiDPI)',
    description: 'Uncapped batch capacity with full CRT vector scanline post-processing, 120Hz support, and keyboard/mouse precision.',
    maxMemoryMB: 128,
    targetFPS: 60,
    batchCapacity: 4096,
    particleLimit: 800,
    enableCRTShader: true,
    enableHaptics: false,
    touchControllerStyle: 'dpad',
    inputPollingRateHz: 240,
    textureFilter: 'nearest',
  },
  raspberry_pi: {
    id: 'raspberry_pi',
    name: 'Raspberry Pi 4 / Embedded',
    description: 'Ultra-low footprint profile with strict 16MB texture pool, aggressive draw call coalescing, and 30/60 FPS lock.',
    maxMemoryMB: 16,
    targetFPS: 60,
    batchCapacity: 512,
    particleLimit: 120,
    enableCRTShader: false,
    enableHaptics: false,
    touchControllerStyle: 'dpad',
    inputPollingRateHz: 60,
    textureFilter: 'nearest',
  },
};
